# Generated by Django 5.0.6 on 2024-06-26 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('active_points', models.IntegerField(default=0)),
                ('expired_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('points_detail', models.JSONField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_earned', models.IntegerField(default=0)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyapp.customerprofile')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_transactions', to='loyaltyapp.shop')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('EARNED', 'Earned'), ('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], default='EARNED', max_length=10)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyapp.customerprofile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyapp.shop')),
            ],
        ),
    ]
