# Generated by Django 5.0.6 on 2024-06-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyapp', '0004_shop_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='merchant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_transactions', to='loyaltyapp.shop'),
        ),
    ]
