# Generated by Django 5.0.6 on 2024-06-27 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyapp', '0005_alter_pointtransaction_merchant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointtransaction',
            name='merchant_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 6, 27)),
        ),
    ]
