# Generated by Django 5.0.6 on 2024-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyapp', '0006_remove_pointtransaction_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
