# Generated by Django 5.0.6 on 2024-06-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyapp', '0008_alter_purchase_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
    ]
